# Generated by Django 3.2.18 on 2023-04-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
