# Generated by Django 3.2.18 on 2023-04-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
        ('Document', '0002_auto_20230417_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Doc_Dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emp.department'),
        ),
    ]
