# Generated by Django 4.2.1 on 2023-06-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_document_doc_content_alter_document_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Doc_Check',
            field=models.IntegerField(null=True),
        ),
    ]
