# Generated by Django 3.2.18 on 2023-04-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_alter_document_doc_dept'),
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newUser',
            new_name='Employee',
        ),
    ]
