# Generated by Django 3.2.18 on 2023-04-17 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certlog',
            name='CLog_Time',
            field=models.DateField(default=datetime.datetime(2023, 4, 17, 11, 38, 7, 530880, tzinfo=utc)),
        ),
    ]
