# Generated by Django 3.2.18 on 2023-04-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('Dept_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Dept_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('User_Email', models.CharField(max_length=50)),
                ('User_Password', models.CharField(max_length=64)),
                ('User_Name', models.CharField(max_length=10)),
                ('User_Rank', models.IntegerField()),
                ('User_Dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.departments')),
            ],
        ),
    ]
