# Generated by Django 3.2.18 on 2023-04-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_auto_20230417_2003'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='newUser',
        ),
    ]
