# Generated by Django 3.2.18 on 2023-04-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_alter_document_doc_dept'),
        ('User', '0002_auto_20230417_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='User_Dept',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='newUser',
        ),
    ]
